In [1]:
# When you create a new instance of EnvironmentData, it'll automatically pull historical data and initialize the database. 
from EnvironmentData import EnvironmentData 
api = EnvironmentData(CatsUserID = 2496, testing = True)
api.readings

Gather readings for Temperature: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.12s/it]
Gather readings for Humidity: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.06s/it]

{'Temperature': {'ReadingType': 'SensorReadingF',
  'data': [],
  'datafile': './data//Temperature-testing.parquet'},
 'Humidity': {'ReadingType': 'SensorReadingRh',
  'data': [],
  'datafile': './data//Humidity-testing.parquet'}}

In [2]:
# Detailed info is saved in the log.
with open('data/EnvironmentData.log', 'r') as file:
    print(file.read())

2024-10-06 22:45:10,043 - EnvironmentData - INFO - initialize_database
2024-10-06 22:45:10,043 - EnvironmentData - INFO - get_sensor_ids
2024-10-06 22:45:10,044 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/cats/user/?ApiKey=XXXX&CatsUserID=XXXX
2024-10-06 22:45:11,042 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21373&ReadingType=SensorReadingF&StartUTC=1720500310&EndUTC=1728276310&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-06 22:45:12,183 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21375&ReadingType=SensorReadingF&StartUTC=1720500310&EndUTC=1728276310&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-06 22:45:13,388 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21377&ReadingType=SensorReadingF&StartUTC=1720500310&EndUTC=1728276310&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-06 22:45:14,409 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21374&ReadingType=SensorReadingRh&StartUTC=1720500310&EndUTC=1728276310&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-06 22:45:15,440 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21376&ReadingType=SensorReadingRh&StartUTC=1720500310&EndUTC=1728276310&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-06 22:45:16,525 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21378&ReadingType=SensorReadingRh&StartUTC=1720500310&EndUTC=1728276310&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-06 22:45:17,582 - EnvironmentData - INFO - Initialize database for Temperature.
2024-10-06 22:45:17,615 - EnvironmentData - INFO - Initialize database for Humidity.

In [3]:
# Data is now in the database.
import polars
polars.read_parquet('data/Humidity-testing.parquet')

shape: (38_880, 3)
┌────────────┬───────────┬──────────┐
│ UTC        ┆ Reading   ┆ SensorID │
│ ---        ┆ ---       ┆ ---      │
│ i64        ┆ f32       ┆ i32      │
╞════════════╪═══════════╪══════════╡
│ 1720500310 ┆ 52.5      ┆ 21374    │
│ 1720500910 ┆ 53.189999 ┆ 21374    │
│ 1720501510 ┆ 53.580002 ┆ 21374    │
│ 1720502110 ┆ 52.919998 ┆ 21374    │
│ 1720502710 ┆ 52.529999 ┆ 21374    │
│ …          ┆ …         ┆ …        │
│ 1728273310 ┆ 62.130001 ┆ 21378    │
│ 1728273910 ┆ 61.400002 ┆ 21378    │
│ 1728274510 ┆ 61.060001 ┆ 21378    │
│ 1728275110 ┆ 60.66     ┆ 21378    │
│ 1728275710 ┆ 60.860001 ┆ 21378    │
└────────────┴───────────┴──────────┘

In [4]:
polars.read_parquet('data/Temperature-testing.parquet')

shape: (38_880, 3)
┌────────────┬───────────┬──────────┐
│ UTC        ┆ Reading   ┆ SensorID │
│ ---        ┆ ---       ┆ ---      │
│ i64        ┆ f32       ┆ i32      │
╞════════════╪═══════════╪══════════╡
│ 1720500310 ┆ 68.629997 ┆ 21373    │
│ 1720500910 ┆ 68.580002 ┆ 21373    │
│ 1720501510 ┆ 68.699997 ┆ 21373    │
│ 1720502110 ┆ 68.650002 ┆ 21373    │
│ 1720502710 ┆ 68.589996 ┆ 21373    │
│ …          ┆ …         ┆ …        │
│ 1728273310 ┆ 70.18     ┆ 21377    │
│ 1728273910 ┆ 70.160004 ┆ 21377    │
│ 1728274510 ┆ 70.089996 ┆ 21377    │
│ 1728275110 ┆ 70.110001 ┆ 21377    │
│ 1728275710 ┆ 70.089996 ┆ 21377    │
└────────────┴───────────┴──────────┘

In [5]:
# Get current readings. 
api.get_current_readings()

# Data is read into new-readings folder for consolidation at the end of the day.
import os
os.listdir('data/new-readings')

['Humidity-1728276317.parquet', 'Temperature-1728276317.parquet']

In [6]:
# To consolidate these into the database, run consolidate_readings.
api.consolidate_readings()
print(os.listdir('data/new-readings'))

[]

In [8]:
polars.read_parquet('data/Temperature-testing.parquet')

# note the increase in row count compared to above.

shape: (38_945, 3)
┌────────────┬───────────┬──────────┐
│ UTC        ┆ Reading   ┆ SensorID │
│ ---        ┆ ---       ┆ ---      │
│ i64        ┆ f32       ┆ i32      │
╞════════════╪═══════════╪══════════╡
│ 1720500310 ┆ 68.629997 ┆ 21373    │
│ 1720500910 ┆ 68.580002 ┆ 21373    │
│ 1720501510 ┆ 68.699997 ┆ 21373    │
│ 1720502110 ┆ 68.650002 ┆ 21373    │
│ 1720502710 ┆ 68.589996 ┆ 21373    │
│ …          ┆ …         ┆ …        │
│ 1728276197 ┆ 20.860001 ┆ 29712    │
│ 1728276227 ┆ 22.18     ┆ 29714    │
│ 1728276211 ┆ 19.879999 ┆ 30133    │
│ 1728276306 ┆ 20.09     ┆ 30135    │
│ 1728276170 ┆ 19.870001 ┆ 30137    │
└────────────┴───────────┴──────────┘